# Site wide configuration

title:            Coven
locale:           en_US
url:              https://www.coven.nu


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false

# Event info
event:
  name: Coven
  tagline: Witch LARP
  logo: skull.jpg
  description: "A Live Action Roleplaying event taking place in Sweden 2015"
  email: coven@example.com
#  twitter: CovenLARP
#  facebook: CovenLARP
  google:
    analytics: 
    verify: 
    ad-client: 
    ad-slot: 

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]
