# Site wide configuration

title:            Coven 18-20 September
locale:           sv
url:              https://www.coven.nu
#url:              http://127.0.0.1:4000


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false

# Event info
event:
  name: Coven
  tagline: a witch LARP
  logo: skull.jpg
  description: "Ett häxlajv i Stockholmsområdet 18-20 september 2015"
  email: svenska@coven.nu
#  twitter: CovenLARP
#  facebook: CovenLARP
  google:
    analytics: 
    verify: 

# Cache invalidation
css:
  timestamp: 2015051303

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]
